version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: "db"
    environment:
      - POSTGRES_DB=snippet07
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5435:5435"
    volumes:
      - database_postgres:/var/lib/postgresql/data
  web:
    build: .
    container_name: "Snippet07"
    environment:
      -DB_USERNAME: "postgres"
      -DB_PASSWORD: "1234"
      -DB_DB: "snippet07"
      -DB_HOST: "db"
      -DB_TABLE: "snippets"
      -DB_PORT: "5435"
    depends_on:
      - db
    ports:
      - "4000:4000"
volumes:
  database_postgres:
networks:
  fullstack:
    driver: bridge